var puzzles = ["PROPERTIES", "COMPUTER", "EXPLOSION", "CHAIRMAN","UNIVERSITY","STATISTICS","BEHAVIORAL","DICTIONARY","AMPLIFIER","LIBRARIAN","PROGRAMMER",
"HOSPITAL","HEADPHONES","ADVENTURE","SUPERVISOR","SPECIALIST","WORDSNAP","JAVASCRIPT","GALACTIC","SUPERNOVA","CELESTIAL",
"ENTERPRISE","HYPERTEXT","PROBABILITY","REPOSITORY","CATEGORY","ADDITIONAL","INTERFACE","STARSTRUCK","MEDIEVAL","POSTCARDS","COALITION","COOPERATE",
"ELEMENTARY","TAXONOMY","CLASSIFIED","SYSTEMATIC","ORGANISM","BACTERIAL","MEDICINAL","ANTIBIOTIC","THEMATICAL","MARKETPLACE","INSTALLED"];
